"""empty message

Revision ID: 9d6fdd90c6a8
Revises: fd9d42c9829a
Create Date: 2021-08-23 10:03:08.917388

"""
from alembic import op
import sqlalchemy as sa
import gino.dialects.asyncpg


# revision identifiers, used by Alembic.
revision = '9d6fdd90c6a8'
down_revision = 'fd9d42c9829a'
branch_labels = None
depends_on = None

contact_statuses = gino.dialects.asyncpg.AsyncEnum(
    'NOT_STARTED', 'OPERATING', 'CANCELLED', 'DONE', name='contractstatus'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('status', contact_statuses, nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    contact_statuses.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
