"""empty message

Revision ID: c41fe5bb5bc0
Revises: 9559b70a8c87
Create Date: 2021-05-18 00:31:55.799059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41fe5bb5bc0'
down_revision = '9559b70a8c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
