"""empty message

Revision ID: d8fe78c473ba
Revises: c41fe5bb5bc0
Create Date: 2021-05-18 12:43:25.192930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fe78c473ba'
down_revision = 'c41fe5bb5bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
